export default class AutoExercise {
  //Signup
  getcheckAutomation = () => cy.contains('Automation')
  getcheckNewUser = () => cy.contains('New User Signup!')
  getcheckEnterAccount = () => cy.contains('Enter Account Information')
  getcheckAccount = () => cy.contains('Account Created!')
  getcheckLogged = () => cy.contains(' Logged in as phquan')
  getcheckDelete = () => cy.contains('Account Deleted!')
  getName = () => cy.get("[type='text']")
  getEmail = () => cy.get("[data-qa='signup-email']")
  getSignUpBtn = () => cy.get('[data-qa="signup-button"]')
  getTitle = () => cy.get('#id_gender1')
  getPassword = () => cy.get('#password')
  getDay = () => cy.get('#days')
  getMonth = () => cy.get('#months')
  getYear = () => cy.get('#years')
  getCheckBox = () => cy.get('#newsletter')
  getCheckBox1 = () => cy.get('#optin')
  getFirstName = () => cy.get('#first_name')
  getLastName = () => cy.get('#last_name')
  getCompany = () => cy.get('#company')
  getAddress = () => cy.get('#address1')
  getAddress2 = () => cy.get('#address2')
  getCountry = () => cy.get('#country')
  getState = () => cy.get('#state')
  getCity = () => cy.get('#city')
  getZipcode = () => cy.get('#zipcode')
  getMobileNumber = () => cy.get('#mobile_number')
  getCreatetBtn = () => cy.get('button[data-qa="create-account"]')
  getContinueBtn = () => cy.get('.btn.btn-primary')
  getContinueDeBtn = () => cy.get('.btn.btn-primary')
  //Login
  getcheckLogin = () => cy.contains('Login to your account')
  getLoginEmail = () => cy.get("[data-qa='login-email']")
  getLoginBtn = () => cy.get('[data-qa="login-button"]')
  getLoginPassword = () => cy.get('[data-qa="login-password"]')
  getLogout = () => cy.get('.fa.fa-lock')
  //login fail
  getcheckLoginFail = () => cy.contains('Your email or password is incorrect!')
  //signup fail
  getcheckSignUpFail = () => cy.contains('Email Address already exist!')
  //Contact
  getContactBtn = () => cy.get('.fa.fa-envelope')
  getcheckContact = () => cy.contains('Get In Touch')
  getNameContact = () => cy.get('[data-qa="name"]')
  getEmailContact = () => cy.get('[data-qa="email"]')
  getSubject = () => cy.get('[data-qa="subject"]')
  getMessage = () => cy.get('[data-qa="message"]')
  getFileBtn = () => cy.get('input[name="upload_file"]')
  getSubmit = () => cy.get('input[data-qa="submit-button"]')
  getcheckSubSuccess = () => cy.contains('Success! Your details have been submitted successfully.')
  getHomeBtn = () => cy.get('.fa.fa-angle-double-left')
  //Test Case  
  getcheckTestCase = () => cy.contains('Below is the list of test Cases for you to practice the Automation. Click on the scenario for detailed Test Steps:')
  //case8
  getCheckProduct = () => cy.contains('All Products')
  getFirstProduct = () => cy.get('.fa.fa-plus-square')
  getcheckNameDetail = () => cy.get('.product-information h2')
  getcheckCategoryDetail = () => cy.contains('Category: Women > Tops')
  getcheckPriceDetail = () => cy.contains('Rs. 500')
  getcheckAvailabilityDetail = () => cy.get('.product-information p b')
  //case9
  getSearch = () => cy.get('#search_product')
  getSearchBtn = () => cy.get('#submit_search')
  getCheckSearch = () => cy.contains('Searched Products')
  getCheckSp = () => cy.get('.features_items')
  //case10
  getdown = () => cy.scrollTo('bottom')
  getCheckSubscription = () => cy.contains('Subscription')
  getSubscribeBtn = () => cy.get('#subscribe')
  getSubscribeEmail = () => cy.get('#susbscribe_email')
  getCheckSubscribeEmail = () => cy.contains('You have been successfully subscribed!')
  //case12
  getAddToCartBtn = () => cy.get('.fa.fa-shopping-cart')
  getContinueShopBtn = () => cy.get('.btn.btn-success.close-modal.btn-block')
  getAddToCart2Btn = () => cy.get('[data-product-id="2"]')
  getViewCart = () => cy.contains('View Cart')
  getCheckPrice = () => cy.get('.cart_price')
  getcheckQuantity = () => cy.get('.disabled')
  getCheckTotal = () => cy.get('.cart_total_price')
  //case13
  getViewProducttBtn = () => cy.get('.fa.fa-plus-square')
  getCheckProductDetail = () => cy.contains('Men Tshirt')
  getQuantity = () => cy.get('#quantity')
  //case14
  getCheckProductDetail1 = () => cy.contains('Blue Top')
  getProceedCheckout = () => cy.get('.btn.btn-default.check_out')
  getRegisterLogin = () => cy.get('.text-center')
  getCheckAddressDetail = () => cy.contains('Address Details')
  getCheckReview = () => cy.contains('Review Your Order')
  getText = () => cy.get('.form-control')
  getplaceOrder = () => cy.get('.btn.btn-default.check_out')
  getNameOnCard = () => cy.get('[data-qa="name-on-card"]')
  getCardNumber = () => cy.get('[data-qa="card-number"]')
  getCVC = () => cy.get('[data-qa="cvc"]')
  getExpiration = () => cy.get('[data-qa="expiry-month"]')
  getY = () => cy.get('[data-qa="expiry-year"]')
  getPayOrder = () => cy.get('[data-qa="pay-button"]')
  getCheckVerifySuccess = () => cy.contains('Your order has been placed successfully!')

}