
export class  Data  {
  username = "phquan"
    email= "phquan" + Math.floor(Math.random() * 1000000).toString().padStart(6, '0') + "@gmail.com"
    password = "123456"
    first_name = "Quan"
    last_name = "Hai"
    company = "Laos"
    address1 = "My Tho"
    address2 = "Can Tho"
    state = "Tot"
    city = "HN"
    zipcode = "8000"
    mobile_number = "099999999"
    day = "5"
    month ="6"
    year = "2003"
    country ="Canada"
    subject = "Jack"
    Message = "Win"
    search ="Men"
    text = "woww"
    cvc ="cm.056"
    expriation = "05"
}
